### PR TITLE
axum-extra: Add serde_json as dev-dependency

### PR DESCRIPTION
**Pull request by programatik29**
## Motivation

`cargo test` compile fail because documentation code use `serde_json` which is an optional dependency.

## Solution

Add `serde_json` as dev-dependency.

### CODE REVIEW

**Review by FrankReh — COMMENTED** [review]
Did the trick for me. Thanks.

**Comment by davidpdrsn** [comment]
Thanks! Merging main should fix CI.

**Review by FrankReh — APPROVED** [review]
I hope you aren't waiting for *me* to approve.

**Comment by programatik29** [comment]
> I hope you aren't waiting for _me_ to approve.

It's probably a good habit to make sure CI passes before merging. I merged main branch to this PR so it should probably pass.

**Review by davidpdrsn — APPROVED** [review]

**Pull request merged**
