### PR TITLE
Support `deserialize_any` for `Path`

### PR DESCRIPTION
**Pull request by davidpdrsn**
Forwarding to `deserialize_str` is probably gonna do the correct thing in most cases. It is also what `serde_urlencoded` does for values (https://github.com/nox/serde_urlencoded/blob/master/src/de.rs#L194-L202)

Fixes https://github.com/tokio-rs/axum/issues/1678

### CODE REVIEW

**Review by jplatte — COMMENTED** [review]
Hmmm thinking about this more, what happens when there are multiple path params?

**Comment by davidpdrsn** [comment]
Oh good catch. That didn't "just work". Not sure why but I'll look into it.

**Comment by jplatte** [comment]
Actually I think we should use forward to the sequence or map deserialize if there's more than one param... Which calls into question whether str for a single parameter really makes that much sense.

**Comment by davidpdrsn** [comment]
I don't quite understand what you mean 🤔 but I think I was able to make all the cases work.

**Comment by jplatte** [comment]
So what do we end up with when using a truly "catch-all" type like `serde_json::Value`, for the different cases (one param / multiple)?

**Comment by davidpdrsn** [comment]
You just get strings. So `/:a` with `Path<Value>` gives `Value::String("foo")`. Same for multiple params. Thats why I was a bit on the fence about this in the first place but I don't think there is much we can do (since path params aren't a self describing format) and forwarding to `deserialize_str` seems like the most useful thing.

**Comment by jplatte** [comment]
What does that mean for multiple parameters? You get them concatenated into one string?

**Comment by davidpdrsn** [comment]
If you do `/:a/:b` you have to use `Path<(Value, Value)>`. `Path<Value>` doesn't work and gives a "wrong number of arguments" error.

**Comment by jplatte** [comment]
Right, I guess that is fine.

**Comment by davidpdrsn** [comment]
I've added a test for that as well.

**Review by jplatte — APPROVED** [review]

**Comment by jplatte** [comment]
(one could kind of expect it to return `Ok(Value::Array(_))` or `Ok(Value::Object(_))` but it's really not that important I think)

**Pull request merged**
