### PR TITLE
migrate all examples to use std::env::var_os instead of std::env::var

### LINKED ISSUE #310: Migrate all examples to use var_os("RUST_LOG").is_none() instead of var("RUST_LOG").is_err()
Reference: https://github.com/tokio-rs/axum/pull/308#pullrequestreview-748870483

### PR DESCRIPTION
**Pull request by Z4RX**
Fixes #310

### CODE REVIEW

**Comment by Z4RX** [comment]
Waiting for #308 being merged

**Comment by jplatte** [comment]
There's a typo in the commit message (second `:` missing between `env` and `var` right at the end).

**Comment by Z4RX** [comment]
@jplatte thx, fixed

**Comment by davidpdrsn** [comment]
#308 is merged 🔥

**Comment by Z4RX** [comment]
@davidpdrsn, jwt example is also updated now

**Pull request merged**
