### PR TITLE
add IntoResponse impl on custom Json extractor example

### LINKED ISSUE #2186: Cannot use wrapped JSON Extractor for responses based on derive_from_request example
The code in the [custom-extractor-error example](https://github.com/tokio-rs/axum/blob/52a90390195e884bcc12ff5bd9fd805cac806447/examples/customize-extractor-error/src/derive_from_request.rs#L21) for deriving `FromRequest` for a custom wrapper Json extractor does not compile as soon as one removes the semicolon in the handler (i.e. actually returning the response that is created from `Json(dbg!(value))`):

```rust
pub async fn handler(Json(value): Json<Value>) -> impl IntoResponse {
    Json(dbg!(value))
}
```

```
error[E0277]: the trait bound `derive_from_request::Json<serde_json::Value>: IntoResponse` is not satisfied
  --> examples/customize-extractor-error/src/derive_from_request.rs:20:69
   |
20 |   pub async fn handler(Json(value): Json<Value>) -> impl IntoResponse {
   |  _____________________________________________________________________^
21 | |     Json(dbg!(value))
22 | | }
   | |_^ the trait `IntoResponse` is not implemented for `derive_from_request::Json<serde_json::Value>`
   |
   = help: the following other types implement trait `IntoResponse`:
             &'static [u8; N]
             &'static [u8]
             &'static str
             ()
             (R,)
             (Response<()>, R)
             (Response<()>, T1, R)
             (Response<()>, T1, T2, R)
           and 133 others

error[E0277]: the trait bound `derive_from_request::Json<serde_json::Value>: IntoResponse` is not satisfied
  --> examples/customize-extractor-error/src/derive_from_request.rs:20:51
   |
20 | pub async fn handler(Json(value): Json<Value>) -> impl IntoResponse {
   |                                                   ^^^^^^^^^^^^^^^^^ the trait `IntoResponse` is not implemented for `derive_from_request::Json<serde_json::Value>`
   |
   = help: the following other types implement trait `IntoResponse`:
             &'static [u8; N]
             &'static [u8]
             &'static str
             ()
             (R,)
             (Response<()>, R)
             (Response<()>, T1, R)
             (Response<()>, T1, T2, R)
           and 133 others

For more information about this error, try `rustc --explain E0277`.
```

Is this intentional? It seems the wrapped extractor does not implement `IntoResponse` and can therefore not be used in the same way as `axum::Json`. Should one still use `axum::Json` in this case for the responses in handlers and only the wrapped one as an extractor?

### PR DESCRIPTION
**Pull request by lennart**
## Motivation

The current custom-extractor-error/derive_from_requst example does not allow the wrapped `Json` extractor to be used as a response. 

## Solution

Adding an impl for `IntoResponse` for the custom extractor provides the same ergonomics as the original `axum::Json`.

__NOTE__: the example now also echoes back the parsed json request body (which it wasn't before and therefore the code did compile without the `impl`) 

edit(jplatte): Closes #2186.

### CODE REVIEW

**Review by jplatte — APPROVED** [review]
Thanks!

**Comment by jplatte** [comment]
Oh, new clippy lints and an ICE from `cargo-public-api-crates` 😅

@lennart to be clear, none of this is related to your PR. We'll fix it separately and merge your PR afterwards.

**Review by davidpdrsn — APPROVED** [review]

**Comment by davidpdrsn** [comment]
CI should pass if you merge the latest main.

**Comment by jplatte** [comment]
No it won't, my PR was incomplete. It only fixed clippy, not cargo-public-api-crates. See also what I sent you on Discord 😅

**Pull request merged**
