### PR TITLE
Refactor initializing tracing-subscriber

### PR DESCRIPTION
**Pull request by tottoto**
Refactoring examples.

### CODE REVIEW

**Review by davidpdrsn — COMMENTED** [review]
Maybe its just me but I actually prefer using `registry()`

**Comment by davidpdrsn** [comment]
@tottoto isn't that what were doing before? 🤔

**Comment by tottoto** [comment]
I think we could use `EnvFilter::try_from_default_env()` in stead of reading `RUST_LOG` maually.

**Comment by tottoto** [comment]
Like this https://github.com/tokio-rs/axum/pull/1596/commits/7fdd414f6e70b7f4d140622ec444131f3b520778.

This change uses [`Envfilter::try_from_default_env()`](https://docs.rs/tracing-subscriber/0.3.16/tracing_subscriber/filter/struct.EnvFilter.html#method.try_from_default_env) reading `RUST_LOG` environment variable.

**Comment by davidpdrsn** [comment]
Ah right yes! Thats a bit nicer indeed :(

**Comment by tottoto** [comment]
Done.

**Review by davidpdrsn — APPROVED** [review]
Thanks!

Really loving these refactoring PRs you've been doing ❤️

**Pull request merged**
