### PR TITLE
Revert "Simplify handler trait (#221)"

### PR DESCRIPTION
**Pull request by davidpdrsn**
This reverts commit 44c58bdf5f43020f92633b7cf79174b1c69cb049.

### CODE REVIEW

**Comment by ZizhengTai** [comment]
What's the reason for reverting this?

**Comment by davidpdrsn** [comment]
It broke @ChillFish8's app.

**Comment by ZizhengTai** [comment]
Do we lose anything (in addition to simpler code) without these simplifications? Like compilation time improvement?

**Comment by davidpdrsn** [comment]
Nope. I was hoping this would improve compile times but it didn't during my testing. Thought it was still worth merging but not if it breaks stuff.

**Comment by ZizhengTai** [comment]
Maybe consider merging it in 0.2?

**Comment by davidpdrsn** [comment]
As it wasnt an important change I don't think we will merge it.

**Pull request merged**
