### PR TITLE
Update to tonic 0.8

### PR DESCRIPTION
**Pull request by tottoto**
## Motivation

Updates tonic to the latest version.

## Solution

Updates crates related to tonic.

### CODE REVIEW

**Review by davidpdrsn — APPROVED** [review]
Thanks!

**Comment by tottoto** [comment]
I'll fix the ci. tonic-build 0.8 depends on prost-build 0.11. This version of prost-build requires a protobuf compiler.

**Comment by tottoto** [comment]
Fixed.

**Review by davidpdrsn — APPROVED** [review]
Thanks!

**Pull request merged**
