### PR TITLE
Fix a typo in `axum::extract::rejection::FailedToDeserializeQueryString` documentation

### PR DESCRIPTION
**Pull request by j3rrywan9**
## Motivation

Fix a typo in public documentation.

## Solution

Fix a typo in public documentation.

### CODE REVIEW

**Review by davidpdrsn — APPROVED** [review]
Thanks!

**Comment by j3rrywan9** [comment]
@davidpdrsn Thanks for the review! Do you happen to know how to go about fixing the failing `cargo-hack` check?

**Comment by davidpdrsn** [comment]
Not sure but it's unrelated to your patch. I'll look into it separately.

**Comment by j3rrywan9** [comment]
@davidpdrsn I created a separate PR https://github.com/tokio-rs/axum/pull/2013 to fix the failing `cargo hack` check.

**Comment by j3rrywan9** [comment]
@davidpdrsn Can you please approve it again? I did a force push after rebase.

**Pull request merged**
