### PR TITLE
Improve `crate-ci/typos` configuration

### PR DESCRIPTION
**Pull request by Turbo87**
see commit messages 😉

### CODE REVIEW

**Comment by jplatte** [comment]
If both are supported (pretty sure they are), I'd prefer using `.typos.toml` over `_typos.toml`.

**Comment by Turbo87** [comment]
I just discovered that we could also use `[workspace.metadata.typos]` in the `Cargo.toml` file. I think that would me my preferred choice, unless you disagree

**Review by jplatte — APPROVED** [review]
Not sure what to think of the config in `Cargo.toml`, really. For cargo plugins it makes sense to me, for more or less entirely language-agnostic tools like typos it feels a little weird. But it's nice to have one file less, I suppose.

**Comment by Turbo87** [comment]
> for more or less entirely language-agnostic tools like typos it feels a little weird

huh, I guess I figured with the org name being `crate-ci` it was somewhat Rust-specific, but you're right, that there isn't much in it that is specific to Rust.

> But it's nice to have one file less, I suppose.

yeah, even two files less in this case :D

**Pull request merged**
