### PR TITLE
Reduce hyper dependency

### PR DESCRIPTION
**Pull request by tottoto**
## Motivation

Reduces `hyper` dependency.

## Solution

Depends on `hyper` only when it is used.

### CODE REVIEW

**Review by jplatte — COMMENTED** [review]
You are implicitly creating a `hyper` feature by not using `dep:` syntax for the feature dependency. I don't think that is what we want, right? I also wonder if any of the features that enable `hyper` + one of its features should be made to not enable hyper. Would have to be reviewed one by one.

**Comment by tottoto** [comment]
Fixed the issue, which I forgot to add the `dep:` prefix.

**Comment by tottoto** [comment]
The mix use of `dep:crate` and `crate/feature` seems to need to be waited until Rust 1.71. So changing `hyper` optional dependency does not seem possible at the moment.

**Comment by jplatte** [comment]
Yes, `"dep:hyper"` and `"hyper/foo"` can't be mixed in older versions but you can just write `"dep:hyper", "hyper?/foo"`, which has the same meaning as `"hyper/foo"`.

**Comment by tottoto** [comment]
Thanks. Fixed to use the workaround.

**Review by jplatte — APPROVED** [review]

**Pull request merged**
