### PR TITLE
Add a way to get 'static Field from Multipart

### PR DESCRIPTION
**Pull request by HK416-is-all-you-need**
Introduce a way to get owned `Field` in order to allow user to satisfy `'static` bounds.

This is necessary to allow user safely access underlying `'static` Field.
It obviously has the same caveat as underlying library, but it is necessary as otherwise you make it impossible to wrap such stream into anything that has `'static + Stream` bounds like `https://docs.rs/rusoto_core/0.47.0/rusoto_core/struct.ByteStream.html`

### CODE REVIEW

**Comment by davidpdrsn** [comment]
I think this particular design choice in multer is quite unfortunate honestly. I think using ownership to check these things statically is way nicer so if possible I would like to keep axum's API the way it is.

If what you're looking for is a fully owned stream of bytes you can do this:

```rust
use axum::extract::multipart::{Multipart, MultipartError};
use std::io;

async fn accept_form(mut multipart: Multipart) {
    let stream = async_stream::stream! {
        while let Some(field) = multipart.next_field().await.map_err(multipart_error_to_io)? {
            yield field.bytes().await.map_err(multipart_error_to_io)
        }
    };

    let bytes_stream = rusoto_core::ByteStream::new(stream);

    // ...
}

fn multipart_error_to_io(err: MultipartError) -> io::Error {
    io::Error::new(io::ErrorKind::Other, err)
}
```

Would this work for you use case? You don't have to use `async_stream` I just find it quite nice in this particular case.

**Comment by HK416-is-all-you-need** [comment]
Using `Field::bytes` is ok if you do not care about efficiency.
I'd prefer allocate by chunks via `Stream`, for simple playground it might be ok, but if we want to have proper solution we need to provide way to get `Stream + 'static` without actually sacrificing benefits of using `Stream` interface.

Right now I have to `transmute` to correct lifetime which is UB because it changes lifetime of reference to `Multipart` object.

If you do not like my idea to expanding API, then how about this:
```rust
pub async fn next_raw_field(&mut self) -> Result<Option<impl Stream + 'static + Send + Sync>, MultipartError> 
```

We can simplify and just return underlying type.
Obviously limitation applies and you have to drop it before using anotehr `next*` call, but I think it is much better than telling user to allocate the whole bunch of memory to read file at once.

**Comment by Kestrer** [comment]
> I think this particular design choice in multer is quite unfortunate honestly.

I originally was going to implement the fully statically checked API, but then [SergioBenitez pointed out how many lifetimes it would infect code with](https://github.com/rousan/multer-rs/pull/33#issuecomment-841697288) so we went with the dynamic one. It probably won't change now, but at least you know why.

**Comment by davidpdrsn** [comment]
> Using Field::bytes is ok if you do not care about efficiency, for simple playground it might be ok.

Can you elaborate on this point? How is using `Field::bytes` inefficient? axum doesn't provide another way of getting at the data so have to call it regardless what API you put on top.

> I originally was going to implement the fully statically checked API, but then SergioBenitez pointed out how many lifetimes it would infect code with so we went with the dynamic one. It probably won't change now, but at least you know why.

Thanks for providing the context 😊

**Comment by HK416-is-all-you-need** [comment]
> axum doesn't provide another way of getting at the data so have to call it regardless what API you put on top.

Ehm... Stream is implemented for `Field`
https://github.com/tokio-rs/axum/blob/main/src/extract/multipart.rs#L98-L107

**Comment by davidpdrsn** [comment]
That forwards for multers stream implementation which is also what the `bytes` method calls. So if you wanted a stream of the individual chunks couldn't that be done with

```rust
let stream = async_stream::stream! {
    while let Some(mut field) = multipart.next_field().await.map_err(multipart_error_to_io)? {
        while let Some(chunk) = field.try_next().await.map_err(multipart_error_to_io)? {
            yield Ok::<_, io::Error>(chunk)
        }
    }
};
```

**Comment by HK416-is-all-you-need** [comment]
This is rather inconvenient because we need to do several checks prior to actually starting pulling data and carrying `Multipart` around for that purpose is rather complicated.
Overall it is possible, but to be blunt it would be easier for me to just implement my own extractor that provides interface that I want rather than going all lengths to work around inconvenient lack of `'static` which could be provided so easily.

**Comment by davidpdrsn** [comment]
Cool. If you're fine with implementing your own extractor then I think thats the better approach. I'll close this for now.

**Comment by martijnarts** [comment]
@HK416-is-all-you-need did you ever end up implementing this extractor?

**Comment by HK416-is-all-you-need** [comment]
@martijnarts you can just copy-paste code from axum and fix lifetimes yourself
There is not much to implement

**Pull request closed without merging**
