### PR TITLE
Add example showing how to handle empty vs missing query params

### PR DESCRIPTION
**Pull request by davidpdrsn**
As discussed in discord. I think it makes sense to have an example for this so we have something to link to when people ask.

### CODE REVIEW

**Comment by jplatte** [comment]
I'm a little worried about offering this as the "one" solution. `String::into_deserializer` + `T::deserialize` might not be suitable for everyone's use cases. `serde_with` offers [a different solution](https://docs.rs/serde_with/1.11.0/serde_with/rust/string_empty_as_none/index.html) that uses `FromStr`, maybe mention that too?

**Comment by davidpdrsn** [comment]
Examples aren't meant to be the one way true way to do something but I see why someone might get that impression. I'll mention `serde_with` as well.

**Comment by jplatte** [comment]
I think this example is also a bit special because the docs link to it.

**Comment by davidpdrsn** [comment]
Yeah thats true. I've updated the example to mention serde_with.

**Review by jplatte — APPROVED** [review]

**Pull request merged**
