### PR TITLE
Add special handling of Extension and Clone for debug_handler

### PR DESCRIPTION
**Pull request by loganbnielsen**
## Motivation

Addresses #2294 using the solution discussed there. ([Link](https://github.com/tokio-rs/axum/issues/2294))

### CODE REVIEW

**Comment by loganbnielsen** [comment]
Am I supposed to do anything to request a review?

**Comment by jplatte** [comment]
No. I can request David's review and maybe also take a look myself (though given that this is mostly stuff that David wrote, I don't want to merge w/o his review), but I don't think it will actually speed up things as there's probably a bandwidth problem, not an awareness problem.

**Comment by loganbnielsen** [comment]
No problem, just wanted to make sure I wasn't dropping the ball

**Review by yanns — APPROVED** [review]
This can have a good value when someone is using `Extension`.

**Comment by jplatte** [comment]
I couldn't see why we would need to special case `Extension` in particular when we already make sure to have good error messages for other extractors such as `Json` so I decided to see what the error message is on `main` with `#[debug_handler]`. Turns out that we don't actually need to do anything, see #2731.

**Pull request closed without merging**
