### PR TITLE
Fix localhost vs 0.0.0.0 discrepancy

### PR DESCRIPTION
**Pull request by mattfbacon**
#1982

### CODE REVIEW

**Comment by davidpdrsn** [comment]
I don't think we should change it everywhere. When you bind on a cloud host you often have to bind to `0.0.0.0` and `127.0.0.1` won't work. I've had that experience on Heroku and heard the same from others. So because people copy/paste our examples I don't think we should change it everywhere.

**Comment by jplatte** [comment]
I think we should actually not change the listen address anywhere, instead we should update the comment(s).

**Comment by davidpdrsn** [comment]
I agree!

**Comment by mattfbacon** [comment]
I agree that people often copy example code. For this reason I find 0.0.0.0 to be an insecure default.

That said, changing the comments is fine too, and maybe adding a clear message about the implications would be enough to resolve the aforementioned issue.

**Comment by mattfbacon** [comment]
Thanks for squashing

**Pull request merged**
