### PR TITLE
Add JWT auth example as community showcase

### PR DESCRIPTION
**Pull request by Z4RX**
## Motivation
#306

### CODE REVIEW

**Comment by Z4RX** [comment]
I'm not sure that this example can belong to `community showcase` probably we need to add a new section

**Review by davidpdrsn — APPROVED** [review]
I think its fine.

**Comment by silvioprog** [comment]
> I'm not sure that this example can belong to `community showcase` probably we need to add a new section

I'm very new to Axum, so sorry for the question, but where is the community showcase page? 😅

**Comment by jplatte** [comment]
https://github.com/tokio-rs/axum/tree/main/examples#community-showcase

**Comment by silvioprog** [comment]
> https://github.com/tokio-rs/axum/tree/main/examples#community-showcase

@jplatte Thanks a lot!

**Pull request merged**
