### PR TITLE
Docs: router wildcards - mention how to capture root path

### PR DESCRIPTION
**Pull request by imbolc**
Mention `Option<Path>` extractor

### CODE REVIEW

**Review by jplatte — COMMENTED** [review]
I think we are intentionally *not* suggesting this because `Path` extraction can fail in other ways than the route not containing the right number of placeholders (for example non-UTF8 bytes in a captured segment).

**Comment by davidpdrsn** [comment]
> I think we are intentionally _not_ suggesting this because `Path` extraction can fail in other ways than the route not containing the right number of placeholders (for example non-UTF8 bytes in a captured segment).

Exactly. See https://github.com/tokio-rs/axum/pull/1663.

My opinion is still that we shouldn't encourage this pattern. I think its better to have

```rust
Router::new()
    .route("/assets/", get(one))
    .route("/assets/*path", get(two));

async fn one() {
    some_shared_function(None).await
}

async fn two(Path(params): Path<String>) {
    some_shared_function(Some(params)).await
}

async fn some_shared_function(params: String) {}
```

**Comment by imbolc** [comment]
Thank you, I didn't notice the discussion. Though the issue seems to be common, I guess you already thought about `Path<Option<T>>`?

**Comment by davidpdrsn** [comment]
`Path` doesn't support deserializing `Option` (https://github.com/tokio-rs/axum/blob/main/axum/src/extract/path/de.rs#L60). Not sure what that would mean and it would probably have the same footgun.

**Comment by imbolc** [comment]
Thank you @jplatte, I'll look into it, closing this one

**Pull request closed without merging**
