### PR TITLE
Move axum crate into workspace subfolder

### PR DESCRIPTION
**Pull request by davidpdrsn**
Over time I imagine we're gonna have other crates in this repo that
provide utilities or integrations for axum. This prepares for that by
moving the main axum crate into its own folder.

~~The README situation is a bit annoying because we want `./README.md`
for viewing the repo on github but `axum/README.md` for crates.io. For
now I've just copy/pasted it and added CI step to make sure they're
identical.~~

### CODE REVIEW

**Comment by jplatte** [comment]
Re. `README.md`, have you tried a symlink in either direction?

**Comment by davidpdrsn** [comment]
I haven't. I'm a bit worried that it'll break how things look on crates.io. [Tokio](https://github.com/tokio-rs/tokio) doesn't do it either which is where I looked first.

**Comment by jplatte** [comment]
What if the root one is the symlink (if GitHub still renders it then)? That can't break crates.io since the workspace root isn't included in crate tarballs.

**Comment by davidpdrsn** [comment]
Good idea! That seems to work https://github.com/tokio-rs/axum/tree/workspace

**Comment by davidpdrsn** [comment]
omg ci is green 🟢 🕺

**Review by jplatte — APPROVED** [review]

**Comment by jplatte** [comment]
GitHub gets really confused when you replace a file with a symlink 😄 

Screenshot_2021-11-03_123258

**Pull request merged**
