### PR TITLE
fix(ws): check connection by header_eq

### PR DESCRIPTION
**Pull request by bestgopher**
## Motivation

I think the `connection` header must be `upgrade`.

### CODE REVIEW

**Review by randomairborne — COMMENTED** [review]
According to [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#field.connection), this header might contain a comma-seperated list of other header names, and may not always just be upgrade. [(this is delineated by the hashtag)](https://www.rfc-editor.org/rfc/rfc9110#name-syntax-notation)

**Comment by bestgopher** [comment]
> According to [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#field.connection), this header might contain a comma-seperated list of other header names, and may not always just be upgrade. [(this is delineated by the hashtag)](https://www.rfc-editor.org/rfc/rfc9110#name-syntax-notation)

Thanks for your reply. But when we use `header_contains`, `Upgradeaaaa` is a valid value.

**Comment by randomairborne** [comment]
Parsing the whole header is likely considered either overkill or not worth the benefit. is an incorrect or malicious client sending this going to cause issues anywhere?

**Comment by bestgopher** [comment]
It's just a requirement of [RFC6455](https://datatracker.ietf.org/doc/html/rfc6455). Is it possible to have multiple values for the `upgrade` header?

**Comment by randomairborne** [comment]
No, I don't believe so. However, the Upgrade header isn't really relevant here.

**Comment by bestgopher** [comment]
> No, I don't believe so. However, the Upgrade header isn't really relevant here.

Okay, I will close the pr. But I still stick to my opinion.

**Pull request closed without merging**
