### PR TITLE
axum 0.8.0-rc.1

### LINKED ISSUE #3060: Add tcp_nodelay removal to changelog
Note to self.

### PR DESCRIPTION
**Pull request by jplatte**
Closes #3060.

@yanns @mladedav I'd love to do another call for testing with all these changes in. @mladedav do you think you're gonna spend some time on the percent-encoded routing thing (not as in code, but as in getting back to the discussion)? Or should we ship without it?

### CODE REVIEW

**Review by yanns — COMMENTED** [review]
Most of users will look at the changelog from axum, and will miss the ones in axum-core. 
I'd suggest to copy/paste the core change log into axum. WDYT?

**Comment by yanns** [comment]
@jplatte What do you think about copy / pasting the change log? Alternatively, we could provide a link from axum to axum-core change log. But I think that the copy / paste is easier for our users.

**Comment by jplatte** [comment]
Sorry, been pretty busy. I think it's gonna be a bit easier to link to the other changelog, but copy-pasting may be easier. Either way I agree that it would be good to have those entries easier to discover.

**Comment by jplatte** [comment]
I've added a note. For the GH release I'll adjust it to point to the right release page.

**Review by yanns — APPROVED** [review]

**Comment by yanns** [comment]
I did the same for https://github.com/tokio-rs/axum/releases/tag/axum-v0.8.0-alpha.1

**Comment by jplatte** [comment]
Huh? But I already had it there? All I see is that the the links to the alpha changelogs seem to be gone now 😕

**Comment by mladedav** [comment]
Sorry, I was (and still am) a bit busier than usual. I'll definitely get back to the percent encoding, but I think we can ship the manor version without it.

**Comment by jplatte** [comment]
I figured as much and moved the percent encoding thing to the 0.9.0 milestone. But maybe that's the wrong place too? I guess it might not even be that clear whether it's going to be breaking.

Anyways, I've added two more things to the 0.8.0 [milestone](https://github.com/tokio-rs/axum/milestone/7) that should probably be done before the release, will spend some time on them over the holidays and probably release around the new year if no new blockers come up.

**Pull request merged**
