### PR TITLE
Add `AppendHeaders`

### PR DESCRIPTION
**Pull request by davidpdrsn**
Fixes https://github.com/tokio-rs/axum/issues/925

### CODE REVIEW

**Review by jplatte — COMMENTED** [review]
This can be part of axum rather than axum-core, no?

**Comment by davidpdrsn** [comment]
I thought so at first but the constructors for `TryIntoHeaderError` are private. So either those have to be made public or this goes into axum-core. I chose the latter but don't feel strongly about it though. Figured since `AppendHeaders` has a very small API its probably fine.

**Comment by jplatte** [comment]
I see. I think it would be fine to have those constructors public, but not clearly better than having `AppendHeaders` in axum-core.

**Review by jplatte — APPROVED** [review]

**Comment by jtk18** [comment]
Why the constant array? Can this be a vec instead? Thank you!

**Comment by davidpdrsn** [comment]
I don't specifically remember. We probably could use any `IntoIterator`.

**Comment by jtk18** [comment]
That would make it much easier to work with. Thank you for the great addition!

**Pull request merged**
