### PR TITLE
Easily convert typed paths into URIs

### PR DESCRIPTION
**Pull request by davidpdrsn**
`#[derive(TypedPath)]` will now also generate `TryFrom<_> for Uri` for
easily converting paths into URIs for use with `Redirect` and friends.

Fixes https://github.com/tokio-rs/axum/issues/789

### CODE REVIEW

**Comment by zys864** [comment]
The `CI / test-versions (stable) (pull_request)`'s command `cargo test --all --all-features --all-targets` failed due to the unexpected `not_send.stderr` which occurs on `stable-1.59`.

I test it on my machine. When I use `stable-1.58` version, the test command successes.

But `stable-1.59` may have update stderr. May be we should fix it,be the test will failed on older rust version.


Here is `stable-1.59` `not_send.stderr`'s `ACTUAL OUTPUT`
````
error: future cannot be sent between threads safely
 --> tests/debug_handler/fail/not_send.rs:4:1
  |
4 | async fn handler() {
  | ^^^^^ future returned by `handler` is not `Send`
  |
  = help: within `impl Future<Output = ()>`, the trait `Send` is not implemented for `Rc<()>`
note: future is not `Send` as this value is used across an await
 --> tests/debug_handler/fail/not_send.rs:6:13
  |
5 |     let rc = std::rc::Rc::new(());
  |         -- has type `Rc<()>` which is not `Send`
6 |     async {}.await;
  |             ^^^^^^ await occurs here, with `rc` maybe used later
7 | }
  | - `rc` is later dropped here
note: required by a bound in `check`
 --> tests/debug_handler/fail/not_send.rs:4:1
  |
4 | async fn handler() {
  | ^^^^^ required by this bound in `check`
````

**Comment by davidpdrsn** [comment]
@zys864 thanks for looking into it! I did think the test failure seemed odd but forgot that a new rust came out yesterday. I'm gonna make a separate PR to fix that in a few hours (have meetings), or you're free to do it if you have the time.

**Comment by davidpdrsn** [comment]
Hm I just thought that this actually is a breaking change. Someone could have implemented `TryFrom<_> for Uri` themselves which will conflict with this but I'm fine with shipping 0.2 of axum-extra and axum-macros.

**Review by jplatte — COMMENTED** [review]
Should the conversion really be fallible? With parameters being url-encoded, the only case where I could see it failing to convert is if the route itself is invalid (in which case registering it would fail too).

**Comment by davidpdrsn** [comment]
Ah yes that's true, doesn't need to be fallible!

**Comment by davidpdrsn** [comment]
@jplatte I've added a `to_uri` method to the `TypedPath` trait. That way its not a breaking change and we don't have to change the macro, since we can parse the `Display` output. What do you think?

**Comment by jplatte** [comment]
I like it! Changelog / docs still reference `TryFrom`, otherwise lgtm.

**Review by jplatte — APPROVED** [review]

**Pull request merged**
