### PR TITLE
Careful! Add utf8_unckecked feature

### PR DESCRIPTION
**Pull request by NateLing**
Like this comment:

```rust
// `ByteStr` can only be constructed from strings which are always valid
// utf-8 so this wont panic.
std::str::from_utf8(&self.0).unwrap()
```

We know it always valid, But axum promise `This crate uses #![forbid(unsafe_code)] to ensure everything is implemented in 100% safe Rust.` 

So, i think we can add a feature that user can use `unsafe` by themself.

### CODE REVIEW

**Comment by jplatte** [comment]
This makes some sense to me and if it shows up on benchmarks I'd be in favor, but *not* if it's behind a feature flag like this.

Personally I think `forbid(unsafe_code)` is overrated, but @davidpdrsn will probably disagree, given he added it to this project 😄

**Comment by NateLing** [comment]
@jplatte  I know this PR breaks Axum's promises, but I think default promises and all promises are different promises. For different consumers, they are free to choose.

**Comment by davidpdrsn** [comment]
This particular use of unsafe is totally fine but yeah I still think we should keep `#[forbid(unsafe)]` unless we have a good reason to remove it. So unless this measurably improves performance then I don't think we should change anything.

Regardless it shouldn't be an optional feature, that feels kinda odd to me 🤷

**Comment by NateLing** [comment]
@davidpdrsn I‘ll add a benchmark, maybe tomorrow

**Comment by davidpdrsn** [comment]
You don't need to add a benchmark to this repo. You can run one of the benchmarks mentioned [here](https://github.com/tokio-rs/axum#performance) and report your results.

**Comment by davidpdrsn** [comment]
I've benchmarked this now and don't see any difference.

Code:

```rust
use axum::{extract::Path, response::IntoResponse, routing::get, Router};
use std::net::SocketAddr;

#[tokio::main]
async fn main() {
    let app = Router::new().route("/:a/:b/:c/:d/:e", get(handler));

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

#[derive(serde::Deserialize)]
struct Params {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
}

async fn handler(_: Path<Params>) -> impl IntoResponse {}
```

Command (each path param is a uuid):

```
wrk \
    -t12 \
    -c400 \
    -d30s \
    http://127.0.0.1:3000/cd0e50d0-db9a-481a-9499-cd0e50d0-db9a-481a-9499-b8179a97a35c/cd0e50d0-db9a-481a-9499-b8179a97a35c/cd0e50d0-db9a-481a-9499-b8179a97a35c/cd0e50d0-db9a-481a-9499-b8179a97a35c/cd0e50d0-db9a-481a-9499-b8179a97a35c
```

Baseline (without unsafe):

```
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.56ms    4.51ms 252.66ms   99.08%
    Req/Sec    15.74k     7.17k   36.37k    56.46%
  5641965 requests in 30.10s, 403.54MB read
  Socket errors: connect 155, read 42, write 0, timeout 0
Requests/sec: 187420.96
Transfer/sec:     13.41MB
```

With unsafe:

```
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.66ms    5.36ms 251.46ms   99.10%
    Req/Sec    15.66k     8.25k   39.13k    53.27%
  5602355 requests in 30.09s, 400.71MB read
  Socket errors: connect 155, read 103, write 0, timeout 0
Requests/sec: 186170.38
Transfer/sec:     13.32MB
```

So actually a small decrease in performance. 187420.96 requests/second to 186170.38 requests/second. That could just be noise but it still isn't an improvement.

@NateLing have you done your own tests?

**Comment by NateLing** [comment]
@davidpdrsn  Not yet, I am busy in this [Add rest and grpc example](https://github.com/tokio-rs/axum/pull/967)

**Comment by davidpdrsn** [comment]
I tested with a handle that used no extractors and that was significantly faster, so I don't think so.

**Comment by NateLing** [comment]
@davidpdrsn I've benchmarked and got a strange result

code:
```rust
use axum::{extract::Path, routing::get, Router};
use std::net::SocketAddr;

#[tokio::main]
async fn main() {
    let app = Router::new().route("/:a/:b/:c/:d/:e", get(handler));

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

#[derive(serde::Deserialize)]
struct Params {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
}

async fn handler(path: Path<Params>) -> String {
    let Path(Params { a, b, c, d, e }) = path;
    [a, b, c, d, e].join("/")
}

```

Profile release

```toml
[profile.release]
strip = false
opt-level = 3
debug = false
debug-assertions = false
overflow-checks =false
lto = "fat"
incremental = false
codegen-units = 1
panic = "abort"
rpath = false
```

rustc --version --verbose

```bash
rustc 1.62.0-nightly (055bf4ccd 2022-04-25)
binary: rustc
commit-hash: 055bf4ccd521c2c2185166c86951be7be145727c
commit-date: 2022-04-25
host: x86_64-apple-darwin
release: 1.62.0-nightly
LLVM version: 14.0.1
```

wrk :

```bash
wrk  -t4  -c100  -d30s  http://127.0.0.1:3000/8fc3a2ac-c504-11ec-9d64-0242ac120002/601da104-eed9-412b-b79d-df8e0dbc311e/008e1845-9be7-4881-b40c-1f16770115ad/0f1041a1-5224-491b-b67f-70fd569bdbdc/b6f2319c-50fa-4343-bb90-cb5ed261d7a8
```
Baseline (without unsafe):
```bash

  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.60ms    1.30ms  22.91ms   70.15%
    Req/Sec     6.15k   506.91    15.36k    77.14%
  735059 requests in 30.10s, 211.70MB read
Requests/sec:  24423.79
Transfer/sec:      7.03MB


  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.60ms    1.30ms  18.30ms   69.85%
    Req/Sec     6.13k   544.66    18.40k    81.64%
  732764 requests in 30.09s, 211.04MB read
Requests/sec:  24354.29
Transfer/sec:      7.01MB


  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.60ms    1.30ms  13.64ms   69.85%
    Req/Sec     6.15k   453.98    11.55k    73.53%
  735911 requests in 30.09s, 211.95MB read
Requests/sec:  24456.03
Transfer/sec:      7.04MB

```
With unsafe:

```bash

  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.72ms    1.34ms  34.41ms   69.89%
    Req/Sec     5.85k   368.87     7.53k    68.29%
  699168 requests in 30.02s, 201.37MB read
Requests/sec:  23290.32
Transfer/sec:      6.71MB


  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.71ms    1.35ms  23.13ms   69.44%
    Req/Sec     5.87k   560.64    20.43k    88.43%
  701511 requests in 30.10s, 202.04MB read
Requests/sec:  23309.25
Transfer/sec:      6.71MB


  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.75ms    1.49ms  37.67ms   74.44%
    Req/Sec     5.81k   444.13    12.69k    76.72%
  694208 requests in 30.09s, 199.94MB read
Requests/sec:  23069.42
Transfer/sec:      6.64MB

```

I really dont know why?

**Comment by NateLing** [comment]
Jemalloc   benchmarked result: 

code:
```rust
use axum::{extract::Path, routing::get, Router};
use std::net::SocketAddr;
use tikv_jemallocator::Jemalloc;

#[global_allocator]
static GLOBAL: Jemalloc = Jemalloc;

#[tokio::main]
async fn main() {
    let app = Router::new().route("/:a/:b/:c/:d/:e", get(handler));

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

#[derive(serde::Deserialize)]
struct Params {
    a: String,
    b: String,
    c: String,
    d: String,
    e: String,
}

async fn handler(path: Path<Params>) -> String {
    let Path(Params { a, b, c, d, e }) = path;
    [a, b, c, d, e].join("/")
}

```

Add `tikv-jemallocator` dependencies

```toml

[dependencies]
tikv-jemallocator = "0.4"

```



wrk :

```bash
wrk  -t4  -c100  -d30s  http://127.0.0.1:3000/8fc3a2ac-c504-11ec-9d64-0242ac120002/601da104-eed9-412b-b79d-df8e0dbc311e/008e1845-9be7-4881-b40c-1f16770115ad/0f1041a1-5224-491b-b67f-70fd569bdbdc/b6f2319c-50fa-4343-bb90-cb5ed261d7a8
```
Baseline (without unsafe):
```bash

  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.53ms    1.37ms  28.26ms   68.48%
    Req/Sec     4.02k   204.65     4.80k    69.19%
  480791 requests in 30.06s, 138.47MB read
Requests/sec:  15994.64
Transfer/sec:      4.61MB

  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.53ms    1.37ms  23.90ms   68.46%
    Req/Sec     4.03k   281.04    10.99k    85.03%
  481595 requests in 30.09s, 138.70MB read
Requests/sec:  16003.09
Transfer/sec:      4.61MB


  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.55ms    1.40ms  29.63ms   69.91%
    Req/Sec     4.01k   218.94     6.51k    74.24%
  478978 requests in 30.06s, 137.95MB read
Requests/sec:  15936.34
Transfer/sec:      4.59MB

```
With unsafe:

```bash

  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.47ms    1.32ms  23.95ms   68.46%
    Req/Sec     4.08k   258.17     9.93k    81.23%
  487489 requests in 30.07s, 140.40MB read
Requests/sec:  16212.90
Transfer/sec:      4.67MB

  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.48ms    1.34ms  20.60ms   68.22%
    Req/Sec     4.08k   300.41    11.92k    88.90%
  488227 requests in 30.10s, 140.61MB read
Requests/sec:  16222.25
Transfer/sec:      4.67MB


  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.47ms    1.32ms  21.23ms   68.55%
    Req/Sec     4.08k   208.42     6.64k    71.80%
  487960 requests in 30.05s, 140.54MB read
Requests/sec:  16236.35
Transfer/sec:      4.68MB

```

Tiny victory.

**Comment by davidpdrsn** [comment]
I think we should just use `Arc<str>` instead. Then there is no need for `unsafe` or `unwrap` at all. I've implemented that in https://github.com/tokio-rs/axum/pull/971 so will close this for now.

**Pull request closed without merging**
