### PR TITLE
Small routing module refactoring

### PR DESCRIPTION
**Pull request by jplatte**
Small things I found while working on #1326.

### CODE REVIEW

**Comment by jplatte** [comment]
Sooo.. The test fails because previously, we had different fallback merging strategies for the `Router` and the `MethodRouter`, specifically when both merged instances have the default, in `Router`s case the "other" fallback was preferred while in `MethodRouter`s case the `self` fallback was preferred. Was that intentional?

**Review by davidpdrsn — APPROVED** [review]

**Comment by davidpdrsn** [comment]
Oh wait sorry. Didn't notice the test failure. I'll look more into this tomorrow.

**Comment by davidpdrsn** [comment]
> the `MethodRouter`, specifically when both merged instances have the default, in `Router`s case the "other" fallback was preferred while in `MethodRouter`s case the `self` fallback was preferred. Was that intentional?

Oh yeah that's not intentional. I think we should pick the "other" fallback, so what `Router` does.

As far as I remember it matters most when the default fallback has middleware.

**Comment by jplatte** [comment]
Since this is is approved and it turned out I didn't need to adjust any tests with the strategy you preferred, I'll merge.

**Pull request merged**
