### PR TITLE
Add XHTML response

### PR DESCRIPTION
**Pull request by kellytk**
Resolves https://github.com/tokio-rs/axum/issues/181.

### CODE REVIEW

**Comment by davidpdrsn** [comment]
Rocket has something similar called Xml which gives a text/xml content type https://docs.rs/rocket/0.4.10/rocket/response/content/struct.Xml.html

What's the difference?

**Comment by kellytk** [comment]
`application/xhtml+xml` is what's [required](https://github.com/tokio-rs/axum/discussions/180#discussion-3521428) for XHTML.

**Comment by davidpdrsn** [comment]
Alright.

I'm actually not sure axum needs built-in support for Xhtml as it's used very rarely. See https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/XHTML

I think users putting this in their own apps, if they need it, is reasonable.

**Comment by kellytk** [comment]
Would it be an option to support modifying a response's header in the handler?  I'd prefer to find a solution that doesn't involve lugging around diffs for a fairly fundamental task.

Re: "used very rarely", even if true, it's still a part of the latest HTML5 spec.

**Comment by kellytk** [comment]
Another idea, would you be open to this PR if XHTML support was behind a feature flag?

**Comment by davidpdrsn** [comment]
> Would it be an option to support modifying a response's header in the handler?

Possibly. If we can find the right api for it. You're welcome to make a proposal in an issue.

> I'd prefer to find a solution that doesn't involve lugging around diffs for a fairly fundamental task.

You can always put this in your own "axum-utils" crate and include that in all your projects.

> Re: "used very rarely", even if true, it's still a part of the latest HTML5 spec.

Some things can still be out of scope. I'd rather provide a good API that users can use to build what's right for their app, rather than building everything into axum. It's a question of balance and where to draw the line.

**Comment by davidpdrsn** [comment]
> Another idea, would you be open to this PR if XHTML support was behind a feature flag?

I don't think so. I would like to reserve feature flags for features that require additional dependencies and/or would be difficult to build yourself. Such as websockets.

**Comment by kellytk** [comment]
I'll make a separate crate, thanks.

**Pull request closed without merging**
