### PR TITLE
Bump version to 0.4.0

### PR DESCRIPTION
**Pull request by davidpdrsn**
Not releasing 0.4.0 yet but work has begun in `main`.

### CODE REVIEW

**Review by jplatte — CHANGES_REQUESTED** [review]
I strongly recommend against bumping the version before doing the release, since this makes it impossible to use the `[patch]` section to replace the released version with what's in the git repo.

**Comment by davidpdrsn** [comment]
Not impossible. This works

```toml
[dependencies]
axum = "0.4"

[patch.crates-io]
axum = { git = "https://github.com/tokio-rs/axum.git", branch = "0.4.0" }
```

[tracing also does it](https://github.com/tokio-rs/tracing/blob/master/tracing/Cargo.toml#L11) and makes it more clear that things have changed to people browsing the code on github.

**Comment by jplatte** [comment]
Yes, it works if your dependency is on "0.4", but since that version is not released nobody is going to have a dependency on 0.4. When trying to use it on a project that (indirectly) depends on 0.3, you get the following warning:

```
warning: Patch `axum v0.4.0 (https://github.com/tokio-rs/axum.git?branch=0.4.0#d173a1a7)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
```

and the `patch` becomes ineffective.

**Comment by davidpdrsn** [comment]
How could that ever work? If we keep the version at 0.3.x there will still be breaking changes which other dependencies cannot incorporate, unless you fork those as well and add a patch.

**Comment by jplatte** [comment]
Other crates depending on axum are likely to only rely on parts of its interface such as `IntoResponse` and `FromResponse`. In such cases, they would continue to work against a `[patch]`ed-in git version.

As an example, let's say I have two crates in separate repos, `axum-extra-extractors` and `my-site`, plus a local workdir of `axum` where I want to experiment with a change to the router that I would later like to upstream if it works out.

If the version in the local workdir is the same as the latest released one, I can simply add `[patch.crates-io]` -> `axum = { path = "../axum" }` to the `my-site` repo and use it that way.
If the version in the local workdir is not the same as the latest released one, I have to either

* change it back, which will likely lead to that change accidentally being committed
* change axum to a path dependency in both my `axum-extra-extractors` workdir (assuming there is one) and `my-site` workdir, and change the `axum-extra-extractors` dependency as well

**Comment by davidpdrsn** [comment]
Alright. I don't think this a big deal regardless.

**Pull request closed without merging**
