### PR TITLE
Release axum, axum-core, and axum-debug

### PR DESCRIPTION
**Pull request by davidpdrsn**

### CODE REVIEW

**Comment by jplatte** [comment]
The `axum` release didn't actually do anything, did it?

**Comment by davidpdrsn** [comment]
It did. The response type is also re-exported from axum https://docs.rs/axum/0.4.1/axum/response/type.Response.html

**Comment by jplatte** [comment]
Right. Then you should have bumped the `axum-core` dependency before releasing, because right now it's possible to upgrade axum to 0.4.1 without upgrading axum-core to 0.1.1 and have axum be broken by that 😉

**Comment by davidpdrsn** [comment]
Ah right. I’ll fix that later today with another release of axum that depends on core 0.1.1. So many crates 😅

**Pull request merged**
