### PR TITLE
Add unix domain socket example

### PR DESCRIPTION
**Pull request by davidpdrsn**
Not actually related to Axum, can be implemented directly with Hyper, but I figure its nice to have for demonstration and might help catch accidental breaking changes in the future.

### CODE REVIEW

**Comment by danielecr** [comment]
Now it is possible to use an unix socket just replacing the line in
https://github.com/tokio-rs/axum/blob/main/examples/hello-world/src/main.rs#L15
with `tokio::net::UnixSocket::bind(path)` and it works with hyper 1.0
the current example is outdated but does something more (really I did not tried what is that peer staff).

It is a good example for connection infos, but really there is missing example for a working unix socket, that would be very short.
Can I do a PR for the smaller version?

**Comment by davidpdrsn** [comment]
> Now it is possible to use an unix socket just replacing the line in
https://github.com/tokio-rs/axum/blob/main/examples/hello-world/src/main.rs#L15
with tokio::net::UnixSocket::bind(path) and it works with hyper 1.0

How? serve requires a TcpListener.

**Comment by davidpdrsn** [comment]
I think perhaps you should just go straight to using hyper directly. I don’t wanna complicate `serve` and friends more than necessary.

The intention is that hyper-util will have higher level conveniences so it makes sense to iterate there, not in axum.

**Comment by danielecr** [comment]
I agree, I am using hyper indeed.
With hyper I just changed 2 lines of code, and it listen on unix socket.

But still your example for using unix socket has been commented out in the newer axum.
And looking at the code in serve there is little diff with hyper example.
I can say the only added staff is IncomingStream.
Still, I didn't looked at tracing or logging staff, and extractors maybe.

**Pull request merged**
