### PR TITLE
Add handle_error to ServiceExt

### PR DESCRIPTION
**Pull request by GuillerLT**
Addition of a new function, handle_error, to the existing trait [ServiceExt](https://docs.rs/axum/latest/axum/trait.ServiceExt.html).

## Motivation

Convenience function for working with tower services.

Before (example)
`let handle_error_service = HandleError::new(service.map_request(foo), bar);`
After (example)
`let handle_error_service = service.map_request(foo).handle_error(bar);`

## Solution

Similar implementation to the functions of [tower::ServiceExt](https://docs.rs/tower/latest/tower/trait.ServiceExt.html).

### CODE REVIEW

**Review by davidpdrsn — COMMENTED** [review]
Thanks!

Do you wanna update the changelog as well?

**Comment by GuillerLT** [comment]
> Do you wanna update the changelog as well?

Done. Thanks for the heads up!

**Review by davidpdrsn — APPROVED** [review]
Thanks!

**Comment by GuillerLT** [comment]
@davidpdrsn looks like auto-merge was disabled when I pushed the last merge. Thanks!

**Pull request merged**
