### PR TITLE
Fixes TSRs redirecting to toplevel inside nested Router

### PR DESCRIPTION
**Pull request by erin-desu**
Originally, if you used `route_with_tsr` (let's say `/nyan/`) inside nested router (let's say `/neko`), it got redirected to `/nyan/`, where `/neko/nyan/` was expected.

Fixed using `OriginalUri` instead of plain `Uri`.

### CODE REVIEW

**Comment by erin-desu** [comment]
CI failure is not my fault :sob:

**Review by mladedav — APPROVED** [review]
Looks good to me, we'll take care of the CI.

@jplatte this adds a dependency from `axum-extra` on `axum`'s `original-uri` feature which adds one uri clone and adds a request extension to each request. I think that should be fine but wanted to doublecheck with you.

**Comment by jplatte** [comment]
Hm, I find that a bit awkward. Maybe we should move `route_with_tsr` behind a feature flag (can be on by default)? Doesn't have to be in this PR though.

**Comment by erin-desu** [comment]
> Hm, I find that a bit awkward. Maybe we should move `route_with_tsr` behind a feature flag (can be on by default)? Doesn't have to be in this PR though.

Well, we are getting Axum 0.8 soon but it's already in alpha and idk if that's a change suited for it? If so i can add it in the fork.

**Comment by jplatte** [comment]
Let's not worry about it in this PR. The way it is now, it can be backported to 0.7.

**Comment by jplatte** [comment]
This has been released as part of axum-extra 0.9.5.

**Pull request merged**
