### PR TITLE
Add `#[debug_middleware]`

### PR DESCRIPTION
**Pull request by davidpdrsn**
Fixes https://github.com/tokio-rs/axum/issues/1985

## TODO

- [x] Docs
- [x] Tests
- [x] Changelog

### CODE REVIEW

**Comment by nipunn1313** [comment]
nice!

**Comment by Vrajs16** [comment]
When will this be merged?

**Comment by davidpdrsn** [comment]
> When will this be merged?

When I take the time to address the comments and clean it up. Don't know when that'll be.

**Comment by VictorElHajj** [comment]
Due to the arcane trait bound errors middlewares are basically useless unless this is merged.

**Comment by yanns** [comment]
I'm continuing the work in https://github.com/tokio-rs/axum/pull/2725
Feedback, review, help welcome

**Comment by jplatte** [comment]
Superseded by the PR linked above.

**Pull request closed without merging**
