### PR TITLE
Fix doc(cfg)s

### LINKED ISSUE #763: docs.rs does not show feature gate on `Multipart` or `WebSocketUpgrade`
For some reason, the docs page does not show the feature gates, but compilation works fine. I suspect this is a docs.rs bug, but I thought it would be better to report it here first:

image

The feature gate for `TypedHeader` is correctly shown

### PR DESCRIPTION
**Pull request by jplatte**
## Motivation

Fixes #763

### CODE REVIEW

**Comment by SaadiSave** [comment]
The error is present in the dependency of an example, and I can confirm that the error is reproducible on the latest `main`:

image

So the error shouldn't block the merging of this PR.

**Comment by jplatte** [comment]
Looks like askama got a new patch release, can't reproduce the error with that locally.

**Comment by jplatte** [comment]
New cargo-deny error:

```
error[B004]: found 2 duplicate entries for crate 'tokio-util'
    ┌─ /github/workspace/Cargo.lock:124:1
    │  
124 │ ╭ tokio-util 0.6.9 registry+[rust-lang/crates.io-index](https://github.com/rust-lang/crates.io-index)
125 │ │ tokio-util 0.7.0 registry+[rust-lang/crates.io-index](https://github.com/rust-lang/crates.io-index)
    │ ╰──────────────────────────────────────────────────────────────────────^ lock entries
    │  
    = tokio-util v0.6.9
      ├── h2 v0.3.11
      │   ├── hyper v0.14.17
      │   │   ├── axum v0.4.4
      │   │   │   └── (dev) axum-core v0.1.1
      │   │   │       └── axum v0.4.4 (*)
      │   │   ├── (dev) axum-core v0.1.1 (*)
      │   │   ├── hyper-rustls v0.23.0
      │   │   │   └── reqwest v0.11.9
      │   │   │       └── (dev) axum v0.4.4 (*)
      │   │   └── reqwest v0.11.9 (*)
      │   └── reqwest v0.11.9 (*)
      ├── reqwest v0.11.9 (*)
      └── tower-http v0.2.2
          ├── (dev) axum v0.4.4 (*)
          └── axum v0.4.4 (*)
    = tokio-util v0.7.0
      └── tower v0.4.12
          ├── (dev) axum v0.4.4
          │   └── (dev) axum-core v0.1.1
          │       └── axum v0.4.4 (*)
          ├── axum v0.4.4 (*)
          └── tower-http v0.2.2
              ├── (dev) axum v0.4.4 (*)
              └── axum v0.4.4 (*)
```

**Comment by davidpdrsn** [comment]
I'll look into the broken deps errors sometime this week. But yeah shouldn't block merging this.

**Pull request merged**
