### PR TITLE
Add Redirect::to constructor

### LINKED ISSUE #248: Add a 303 constructor to Redirect
### Motivation

This should be the go-to redirect response code for GET-only redirects. Rocket even has this as [`Redirect::to`](https://docs.rs/rocket/0.4.10/rocket/response/struct.Redirect.html#method.to) (the other constructors have the same names as the ones in axum).

### Proposal

Add a constructor to `Redirect` for creating a 303 response. I don't care much about the name, `Redirect::to` like in Rocket or `Redirect::see_other` seem like viable options.

### Alternatives

Provide a constructor with a status code parameter. I don't think this is actually a good idea, and it was intentionally left out so far too.

### PR DESCRIPTION
**Pull request by jplatte**
The motivation for this is established in the issue it fixes.

Resolves #248

### CODE REVIEW

**Comment by jplatte** [comment]
Seems like I can't get GitHub to register this PR as closing #248 :confused:

**Comment by davidpdrsn** [comment]
Looks alright for me

image

**Review by davidpdrsn — COMMENTED** [review]
Wanna add a note to the changelog as well?

**Comment by jplatte** [comment]
Oh I thought if it just said "Linked" it wouldn't auto-close. For some reason it doesn't show that small text for me.

**Pull request merged**
